<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */
            echo __('Abandoned Cart Line Chart') ?></span>
    </div>
    <br/>
    <div class="admin__page-section-content">
        <div id="abandoned_cart_line_chart" style="clear: both;"></div>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */
            echo __('Abandoned Cart Rates') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div id="abandoned_cart_chart" style="float: left"></div>
        <div id="guest_abandoned_cart_chart" style="float: left"></div>
    </div>


</section>