<?php
/**
* Magedelight
* Copyright (C) 2017 Magedelight <info@magedelight.com>
*
* @category Magedelight
* @package Magedelight_Monerisca
* @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
* @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
* @author Magedelight <info@magedelight.com>
*/
?>
<?php $cards = $block->getCustomerCards(); ?>

<button type="button" title="<?php echo $block->escapeHtml(__("Add New Card")) ?>"
        class="addcardbutton button action primary <?php if (empty($cards)) :
    ?> addmargin
        <?php endif; ?>
        " onclick="window.location = '<?php echo $block->escapeXssInUrl($block->getAddCardUrl()) ?>';">
    <span>
        <span><?php echo $block->escapeHtml(__("Add New Card")) ?></span>
    </span>
</button>
<?php if (!empty($cards)) : ?>
    <table class="data-table cards" id="my-saved-cards-table">
        <col />
        <col />
        <col width="1"/>
        <thead>
            <tr>
                <th class="a-left view"><?php echo $block->escapeHtml(__('Card #')) ?></th>
                <th class="a-left view"><?php echo $block->escapeHtml(__('Card Info')) ?></th>
                <th class="a-center view"><?php echo $block->escapeHtml(__('Action')) ?></th>
            </tr>
        </thead>
        <tbody>
            <?php $_odd = ''; ?>
            <?php foreach ($cards as $_card) : ?>
                <tr>
                    <td class="a-left view"><strong><?php echo $block->escapeHtml("XXXX-".$_card['cc_last_4']) ?>
                        </strong></td>
                    <td class="a-left view"><?php /* @escapeNotVerified */ echo $block->getAddressHtml($_card); ?></td>
                    <td class="a-center view">
                        <span class="nobr">
                            <form method="post" name="form_edit_<?php echo $block->escapeHtml($_card['card_id']) ?>"
                                  action="<?php echo $block->escapeXssInUrl($block->getPostUrl()) ?>"
                                  style="display:inline-block;">
                                <input type="hidden" name="card_id"
                                       value="<?php echo $block->escapeHtml($_card['card_id']) ?>" />
                                <button class="button action primary" name="profile_edit" value="edit" type="submit">
                                    <span><span><?php echo $block->escapeHtml(__("Edit")) ?></span></span></button>
                            </form>
                            <span class="separator">&nbsp;|&nbsp;</span>
                            <form onsubmit="return confirm('Are you sure want to delete credit card details?');"
                                  method="post" id="form_delete_<?php echo $block->escapeHtml($_card['card_id']) ?>"
                                  name="form_delete_<?php echo $block->escapeHtml($_card['card_id']) ?>"
                                  action="<?php echo $block->escapeXssInUrl($block->getDeleteAction()) ?>"
                                  style="display:inline-block;">
                                <input type="hidden" name="card_id"
                                       value="<?php echo $block->escapeHtml($_card['card_id']) ?>" />
                                <button class="button action primary" name="profile_delete" value="delete"
                                        type="submit"><span>
                                        <span>
                                            <?php /* @noEscape */ echo __("Delete") ?></span>
                                    </span>
                                </button>
                            </form>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else : ?>
    <div class="message info empty">
        <span><?php /* @noEscape */ echo __('You have no saved credit cards.') ?></span></div>
<?php endif;
