<?php
/**
* Magedelight
* Copyright (C) 2017 Magedelight <info@magedelight.com>
*
* @category Magedelight
* @package Magedelight_Monerisca
* @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
* @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
* @author Magedelight <info@magedelight.com>
*/
?>
<?php
$cards = $block->getCards()
    ?>
<div class="ui-tabs" id="md-monerisca-cards-list-container">
    <ul class="md-monerisca-cards-list ui-tabs-nav">
        <?php foreach ($cards as $idx => $_card) : ?>
        <li class="md-monerisca-cards-list-item">
            <div class="md-monerisca-cards-list-item-actions">
                <button class="action-edit" type="button" customer-card-id="<?php
                echo $block->escapeHtml($_card["card_id"]) ?>"
                edit_url="<?php echo $block->escapeXssInUrl($block->getEditCardAction()); ?>">
                        <span></span>
                </button>
                <button class="action-delete" type="button" customer-card-id="<?php
                echo (string)$block->escapeHtml($_card["card_id"]) ?>"
                delete_url="<?php echo $block->escapeXssInUrl($block->getDeleteActionUrl()); ?>">
                        <span></span>
                </button>
            </div>
            <div>
                <strong><?php /* @noEscape */ echo "XXXX-" . $_card["cc_last_4"]; ?></strong>
            </div>
            <address>
                <?php /* @noEscape */  echo $block->getFormatedAddress($_card) ?>
            </address>
        </li>
        <?php endforeach; ?>
        <li class="md-monerisca-cards-actions last">
            <button type="button" add_new_url="<?php
                    echo $block->escapeXssInUrl($block->getAddAction()); ?>" class="scalable add"
                    onclick="addNewForm('<?php
                    echo $block->escapeXssInUrl($block->getAddAction()); ?>')" id="md-cards-add">
                <span><?php echo $block->escapeHtml(__('Add New Card')) ?></span>
            </button>
        </li>
    </ul>
    <div class="md-monerisca-cards-item-edit ">
        <div class="md-monerisca-cards-item-edit-content address-item-edit-content">
            <fieldset class="admin__fieldset md-monerisca-cards-item-edit-fieldset">
                <?php /* @escapeNotVerified */  echo $block->getChildHtml('monerisAddCards'); ?>
            </fieldset>
        </div>
    </div>
</div>