<?php
//phpcs:disable PSR2.Methods.FunctionCallSignature.SpaceBeforeOpenBracket
//phpcs:disable Magento2.Security.IncludeFile.FoundIncludeFile
?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\Order\Packaging */ ?>
<?php
$shippingMethod = $block->getShipment()->getOrder()->getShippingMethod();
$sizeSource = $block->getSourceSizeModel()->toOptionArray();
$girthEnabled = $block->isDisplayGirthValue() && $block->isGirthAllowed() ? 1 : 0;
?>
<?php
/** @var \Mageside\CanadaPostShipping\Helper\Carrier $carrierHelper */
$carrierHelper = $this->helper(Mageside\CanadaPostShipping\Helper\Carrier::class);
?>
<script>
    require([
        "jquery",
        "prototype",
        "Magento_Shipping/order/packaging",
        "Magento_Ui/js/modal/modal"
    ], function(jQuery){

        window.packaging = new Packaging(<?= /* @noEscape */ $block->getConfigDataJson() ?>);
        packaging.changeContainerType($$('select[name=package_container]')[0]);
        packaging.checkSizeAndGirthParameter(
            $$('select[name=package_container]')[0],
            <?= /* @noEscape */ $girthEnabled ?>
        );
        packaging.setConfirmPackagingCallback(function(){
            packaging.setParamsCreateLabelRequest($('edit_form').serialize(true));
            <?php if ($carrierHelper->canChooseManifest()) : ?>
            packaging.setParamsCreateLabelRequest({'shipment[canadapost_manifest_id]': jQuery('[name="shipment[canadapost_manifest_id]"]').val()});
            <?php endif ?>
            <?php if ($carrierHelper->canShipByCanadaPost($block->getShipment()->getOrder())) : ?>
                packaging.setParamsCreateLabelRequest({'shipment[canadapost_shipping_method]': jQuery('[name="shipment[canadapost_shipping_method]"]').val()});
            <?php endif ?>
            packaging.sendCreateLabelRequest();
        });
        packaging.setLabelCreatedCallback(function(response){
            setLocation("<?= $block->escapeJs($block->escapeUrl($block->getUrl(
                'sales/order/view',
                ['order_id' => $block->getShipment()->getOrderId()]
            ))); ?>");
        });
        packaging.setCancelCallback(function() {
            if ($('create_shipping_label')) {
                packaging.cleanPackages();
                $('create_shipping_label').checked = false;
                toggleCreateLabelCheckbox();
            }
        });
        packaging.setItemQtyCallback(function(itemId){
            var item = $$('[name="shipment[items]['+itemId+']"]')[0];
            if (item && !isNaN(item.value)) {
                return item.value;
            }
        });
        jQuery('#packaging_window').modal({
            type: 'slide',
            title: '<?= $block->escapeJs($block->escapeHtml(__('Create Packages'))) ?>',
            buttons: [{
                text: '<?= $block->escapeJs($block->escapeHtml(__('Cancel'))) ?>',
                'class': 'action-secondary',
                click: function () {
                    packaging.cancelPackaging();
                    this.closeModal();
                    }
                }, {
                text: '<?= $block->escapeJs($block->escapeHtml(__('Save'))) ?>',
                'attr': {'disabled':'disabled', 'data-action':'save-packages'},
                'class': 'action-primary _disabled',
                click: function () {
                    packaging.confirmPackaging();
                    }
                }, {
                    text: '<?= $block->escapeJs($block->escapeHtml(__('Add Package'))) ?>',
                    'attr': {'data-action':'add-packages'},
                    'class': 'action-secondary',
                    click: function () {
                        packaging.newPackage();
                    }
            }]
        });
        jQuery(document).trigger('packaging:inited');
        jQuery(document).data('packagingInited', true);
    });
</script>

<!-- Edited template Magento_Shipping::order/packaging/popup_content.phtml start here: -->
<!-- Added manifests dropdown -->
<!-- Added preselect measurements by store configs -->

<?php
$isMetric = $carrierHelper->isMeasuresMetric($this->getShipment()->getStoreId());
$selected = true;
?>
<div id="packaging_window">
    <div class="message message-warning" style="display: none"></div>

    <?php if ($carrierHelper->canChooseManifest()) : ?>
        <div class="admin__field">
            <label class="admin__field-label">Choose Canada Post Manifest</label>
            <div class="admin__field-control">
                <select name="shipment[canadapost_manifest_id]" class="admin__control-select">
                    <option value="new">
                        <?= $block->escapeHtml(__('Create New Canada Post Manifest')) ?>
                    </option>
                    <?php foreach ($carrierHelper->getAvailableManifests() as $manifestId) : ?>
                        <option <?= $selected ? 'selected' : '' ?> value="<?= $block->escapeHtml($manifestId) ?>">
                            <?= $block->escapeHtml('#' . $manifestId) ?>
                        </option>
                        <?php $selected = false; ?>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif ?>

    <?php $order = $block->getShipment()->getOrder(); ?>
    <?php if ($carrierHelper->canShipByCanadaPost($order)) : ?>
        <?php $selected = true; ?>
        <div class="admin__field">
            <label class="admin__field-label">Choose Canada Post Shipping Method</label>
            <div class="admin__field-control">
                <select name="shipment[canadapost_shipping_method]" class="admin__control-select">
                    <?php foreach ($carrierHelper->getCanadaPostShippingMethods($order) as $method) : ?>
                        <option <?= $selected ? 'selected' : '' ?> value="<?= $block->escapeHtml($method['code']) ?>">
                            <?= $block->escapeHtml($method['title']) ?>
                        </option>
                        <?php $selected = false; ?>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif ?>

    <section class="admin__page-section" id="package_template" style="display:none;">
        <div class="admin__page-section-title">
            <span class="title">
                <?= $block->escapeHtml(__('Package')) ?> <span data-role="package-number"></span>
            </span>
            <div class="actions _primary">
                <button type="button"
                        class="action-secondary"
                        data-action="package-save-items"
                        onclick="packaging.packItems(this);">
                    <span><?= $block->escapeHtml(__('Add Selected Product(s) to Package')) ?></span>
                </button>
                <button type="button"
                        class="action-secondary"
                        data-action="package-add-items"
                        onclick="packaging.getItemsForPack(this);">
                    <span><?= $block->escapeHtml(__('Add Products to Package')) ?></span>
                </button>
            </div>
        </div>
        <div class="admin__control-table-wrapper admin__page-subsection">
            <table class="data-table admin__control-table">
                <thead>
                <tr>
                    <th class="col-type"><?= $block->escapeHtml(__('Type')) ?></th>
                    <?php if ($girthEnabled == 1) : ?>
                        <th class="col-size"><?= $block->escapeHtml(__('Size')) ?></th>
                        <th class="col-girth"><?= $block->escapeHtml(__('Girth')) ?></th>
                        <th>&nbsp;</th>
                    <?php endif; ?>
                    <th class="col-custom" <?= $block->displayCustomsValue() ? '' : 'style="display: none;"' ?>>
                        <?= $block->escapeHtml(__('Customs Value')) ?>
                    </th>
                    <th class="col-total-weight"><?= $block->escapeHtml(__('Total Weight')) ?></th>
                    <th class="col-length"><?= $block->escapeHtml(__('Length')) ?></th>
                    <th class="col-width"><?= $block->escapeHtml(__('Width')) ?></th>
                    <th class="col-height"><?= $block->escapeHtml(__('Height')) ?></th>
                    <th>&nbsp;</th>
                    <?php if ($block->getDeliveryConfirmationTypes()) : ?>
                        <th class="col-signature"><?= $block->escapeHtml(__('Signature Confirmation')) ?></th>
                    <?php endif; ?>
                    <th class="col-actions">&nbsp;</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="col-type">
                        <?php $containers = $block->getContainers(); ?>
                        <select name="package_container"
                                onchange="packaging.changeContainerType(this);packaging.checkSizeAndGirthParameter(this, <?= $block->escapeHtmlAttr($block->escapeJs($girthEnabled)) ?>);"
                            <?php if (empty($containers)) : ?>
                                title="<?= $block->escapeHtmlAttr(__('USPS domestic shipments don\'t use package types.')) ?>"
                                disabled=""
                                class="admin__control-select disabled"
                            <?php else : ?>
                                class="admin__control-select"
                            <?php endif; ?>>
                            <?php foreach ($containers as $key => $value) : ?>
                                <option value="<?= $block->escapeHtmlAttr($key) ?>" >
                                    <?= $block->escapeHtml($value) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <?php if ($girthEnabled == 1 && !empty($sizeSource)) : ?>
                        <td>
                            <select name="package_size"
                                    class="admin__control-select"
                                    onchange="packaging.checkSizeAndGirthParameter(this, <?= $block->escapeHtmlAttr($block->escapeJs($girthEnabled)) ?>);">
                                <?php foreach ($sizeSource as $key => $value) : ?>
                                    <option value="<?= $block->escapeHtmlAttr($sizeSource[$key]['value']) ?>">
                                        <?= $block->escapeHtml($sizeSource[$key]['label']) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td>
                            <input type="text"
                                   class="input-text admin__control-text validate-greater-than-zero"
                                   name="container_girth" />
                        </td>
                        <td>
                            <select name="container_girth_dimension_units"
                                    class="options-units-dimensions measures admin__control-select"
                                    onchange="packaging.changeMeasures(this);">
                                <option value="<?= /* @noEscape */ Zend_Measure_Length::INCH ?>" <?= !$isMetric ? 'selected="selected"' : '' ?>><?= $block->escapeHtml(__('in')) ?></option>
                                <option value="<?= /* @noEscape */ Zend_Measure_Length::CENTIMETER ?>" <?= $isMetric ? 'selected="selected"' : '' ?>><?= $block->escapeHtml(__('cm')) ?></option>
                            </select>
                        </td>
                    <?php endif; ?>
                    <?php
                    if ($block->displayCustomsValue()) {
                        $customsValueDisplay = '';
                        $customsValueValidation = ' validate-zero-or-greater ';
                    } else {
                        $customsValueDisplay = ' style="display: none;" ';
                        $customsValueValidation = '';
                    }
                    ?>
                    <td class="col-custom" <?= /* @noEscape */ $customsValueDisplay ?>>
                        <div class="admin__control-addon">
                            <input type="text"
                                   class="customs-value input-text admin__control-text <?= /* @noEscape */ $customsValueValidation ?>"
                                   name="package_customs_value" />
                            <span class="admin__addon-suffix">
                                    <span class="customs-value-currency">
                                        <?= $block->escapeHtml($block->getCustomValueCurrencyCode()) ?>
                                    </span>
                                </span>
                        </div>
                    </td>
                    <td class="col-total-weight">
                        <div class="admin__control-addon">
                            <input type="text"
                                   class="options-weight input-text admin__control-text required-entry validate-greater-than-zero"
                                   name="container_weight" />
                            <select name="container_weight_units"
                                    class="options-units-weight measures admin__control-select"
                                    onchange="packaging.changeMeasures(this);">
                                <option value="<?= /* @noEscape */ Zend_Measure_Weight::POUND ?>" <?= !$isMetric ? 'selected="selected"' : '' ?>><?= $block->escapeHtml(__('lb')) ?></option>
                                <option value="<?= /* @noEscape */ Zend_Measure_Weight::KILOGRAM ?>" <?= $isMetric ? 'selected="selected"' : '' ?>><?= $block->escapeHtml(__('kg')) ?></option>
                            </select>
                            <span class="admin__addon-prefix"></span>
                        </div>
                    </td>
                    <td class="col-length">
                        <input type="text"
                               class="input-text admin__control-text validate-greater-than-zero"
                               name="container_length" />
                    </td>
                    <td class="col-width">
                        <input type="text"
                               class="input-text admin__control-text validate-greater-than-zero"
                               name="container_width" />
                    </td>
                    <td class="col-height">
                        <input type="text"
                               class="input-text admin__control-text validate-greater-than-zero"
                               name="container_height" />
                    </td>
                    <td class="col-measure">
                        <select name="container_dimension_units"
                                class="options-units-dimensions measures admin__control-select"
                                onchange="packaging.changeMeasures(this);">
                            <option value="<?= /* @noEscape */ Zend_Measure_Length::INCH ?>" <?= !$isMetric ? 'selected="selected"' : '' ?>><?= $block->escapeHtml(__('in')) ?></option>
                            <option value="<?= /* @noEscape */ Zend_Measure_Length::CENTIMETER ?>" <?= $isMetric ? 'selected="selected"' : '' ?>><?= $block->escapeHtml(__('cm')) ?></option>
                        </select>
                    </td>
                    <?php if ($block->getDeliveryConfirmationTypes()) : ?>
                        <td>
                            <select name="delivery_confirmation_types" class="admin__control-select">
                                <?php foreach ($block->getDeliveryConfirmationTypes() as $key => $value) : ?>
                                    <option value="<?= $block->escapeHtmlAttr($key) ?>" >
                                        <?= $block->escapeHtml($value) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    <?php endif; ?>
                    <td class="col-actions">
                        <button type="button"
                                class="action-delete DeletePackageBtn"
                                onclick="packaging.deletePackage(this);">
                            <span><?= $block->escapeHtml(__('Delete Package')) ?></span>
                        </button>
                    </td>
                </tr>
                </tbody>
            </table>
            <?php if ($block->getContentTypes()) : ?>
                <table class="data-table admin__control-table" cellspacing="0">
                    <thead>
                    <tr>
                        <th><?= $block->escapeHtml(__('Contents')) ?></th>
                        <th><?= $block->escapeHtml(__('Explanation')) ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <select name="content_type"
                                    class="admin__control-select"
                                    onchange="packaging.changeContentTypes(this);">
                                <?php foreach ($block->getContentTypes() as $key => $value) : ?>
                                    <option value="<?= $block->escapeHtmlAttr($key) ?>" >
                                        <?= $block->escapeHtml($value) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td>
                            <input name="content_type_other"
                                   type="text"
                                   class="input-text admin__control-text options-content-type disabled"
                                   disabled="disabled" />
                        </td>
                    </tr>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
        <div class="admin__page-subsection" data-role="package-items">
            <div class="grid_prepare admin__page-subsection"></div>
        </div>
    </section>
    <div id="packages_content"></div>
</div>
