<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<fieldset class="admin__fieldset" id="export_filter_container" style="display:none;">
    <legend class="admin__legend">
        <span><?= /* @escapeNotVerified */ __('Entity Attributes') ?></span>
    </legend>
    <br />
    <form id="export_filter_form" action="<?= /* @escapeNotVerified */ $block->getUrl('*/*/export') ?>" method="post">
        <input name="form_key" type="hidden" value="<?= /* @escapeNotVerified */ $block->getFormKey() ?>" />
        <div id="export_filter_grid_container"><!-- --></div>
    </form>
    <button class="action- scalable" type="button" onclick="getFile();"><span><?php
        /* @escapeNotVerified */ echo __('Continue')
    ?></span></button>
</fieldset>
<script>
require(['prototype'], function(){

//<![CDATA[
   $('entity').selectedIndex = 0; // forced resetting entity selector after page refresh
//]]>

});
   function selectAllChecks() {
    // class admin__control-checkbox is selector 
        var inputs = document.getElementsByClassName("admin__control-checkbox");
        for(var i = 0; i < inputs.length; i++) {
            if(inputs[i].type == "checkbox") {
                inputs[i].checked = true;
            }
        }
    };
</script>
