<?php
/**
* Magedelight
* Copyright (C) 2017 Magedelight <info@magedelight.com>
*
* @category Magedelight
* @package Magedelight_Monerisca
* @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
* @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
* @author Magedelight <info@magedelight.com>
*/
?>
<?php $methodCode = "md_monerisca"; ?>

<form action="<?php echo $block->escapeXssInUrl($block->getSaveUrl()) ?>" name="monerisca_add_card"
      data-hasrequired="<?php echo $block->escapeHtml(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'id="monerisca_add_card" method="post">
    <fieldset class="fieldset">
        <h2 class="legend"><?php echo $block->escapeHtml(__('Contact Information')) ?></h2>
        <?php /* @escapeNotVerified */ echo $block->getBlockHtml('formkey') ?>
        <div class="field name-firstname required">
            <label for="<?php echo $block->escapeHtml($methodCode) ?>_firstname" class="label">
                <?php echo $block->escapeHtml(__('First Name')) ?>
            </label>
            <div class="control">
                <input type="text" id="<?php echo $block->escapeHtml($methodCode) ?>_firstname"
                       name="<?php echo $block->escapeHtml($methodCode) ?>[address_info][firstname]"
                       value="" title="<?php echo $block->escapeHtml(__('First Name')) ?>" maxlength="255"
                       class="input-text required-entry" />
            </div>
        </div>
        <div class="field name-lastname required">
            <label for="<?php echo $block->escapeHtml($methodCode) ?>_lastname" class="label">
                <?php echo $block->escapeHtml(__('Last Name')) ?></label>
            <div class="control">
                <input type="text" id="<?php echo $block->escapeHtml($methodCode) ?>_lastname"
                       name="<?php echo $block->escapeHtml($methodCode) ?>[address_info][lastname]" value=""
                       title="<?php echo $block->escapeHtml(__('Last Name')) ?>" maxlength="255"
                       class="input-text required-entry">
            </div>
        </div>
        <div class="field">
            <label for="<?php echo $block->escapeHtml($methodCode) ?>_company" class="label">
                <?php echo $block->escapeHtml(__('Company')) ?></label>
            <div class="control">
                <input type="text" name="<?php echo $block->escapeHtml($methodCode) ?>[address_info][company]"
                       id="<?php echo $block->escapeHtml($methodCode) ?>_company"
                       title="<?php echo $block->escapeHtml(__('Company')) ?>" value="" class="input-text ">
            </div>
        </div>
        <div class="field required">
            <label for="<?php echo $block->escapeHtml($methodCode) ?>_street" class="label">
                <?php echo $block->escapeHtml(__('Street Address')) ?></label>
            <div class="control">
                <input type="text" name="<?php echo $block->escapeHtml($methodCode) ?>[address_info][street]" value=""
                       title="<?php echo $block->escapeHtml(__('Street Address')) ?>"
                       id="<?php echo $block->escapeHtml($methodCode) ?>_street" class="input-text  required-entry">
            </div>
        </div>

        <div class="field city required">
            <label for="<?php echo $block->escapeHtml($methodCode) ?>_city" class="label">
                <?php echo $block->escapeHtml(__('City')) ?></label>
            <div class="control">
                <input type="text" name="<?php echo $block->escapeHtml($methodCode) ?>[address_info][city]" value=""
                       title="<?php echo $block->escapeHtml(__('City')) ?>" class="input-text  required-entry"
                       id="<?php echo $block->escapeHtml($methodCode) ?>_city">
            </div>
        </div>
        <div class="field required state-required">
            <label for="<?php echo $block->escapeHtml($methodCode) ?>_region_id" class="label">
                <?php echo $block->escapeHtml(__('State/Province')) ?></label>
            <div class="control">
                <select id="<?php echo $block->escapeHtml($methodCode) ?>_region_id"
                        name="<?php echo $block->escapeHtml($methodCode) ?>[address_info][region_id]"
                        title="<?php echo $block->escapeHtml(__('State/Province')) ?>" class="validate-select" >
                    <option value=""><?php echo $block->escapeHtml(__('Please select region, state or province'))
                        ?></option>
                </select>

                <input type="text" id="<?php echo $block->escapeHtml($methodCode) ?>_state"
                       name="<?php echo $block->escapeHtml($methodCode) ?>[address_info][state]"
                       title="<?php echo $block->escapeHtml(__('State/Province')) ?>"
                       class="input-text required-entry" value="" />
            </div>
        </div>

        <div class="field zip required">
            <label for="<?php echo $block->escapeHtml($methodCode) ?>_zip" class="label">
                <?php echo $block->escapeHtml(__('Zip/Postal Code')) ?></label>
            <div class="control">
                <input type="text" name="<?php echo $block->escapeHtml($methodCode) ?>[address_info][postcode]"
                       value=""
                       title="<?php echo $block->escapeHtml(__('Zip')) ?>"
                       id="<?php echo $block->escapeHtml($methodCode) ?>_zip"
                       class="input-text validate-zip-international  required-entry">
            </div>
        </div>
        <div class="field">
            <label for="country" class="label"><?php echo $block->escapeHtml(__('Country')) ?></label>
            <div class="control">
                <?php /* @escapeNotVerified */ echo $block->getCountryHtmlSelect() ?>
            </div>
        </div>


        <div class="field telephone required">
            <label for="<?php echo $block->escapeHtml($methodCode) ?>_telephone" class="label">
                <?php echo $block->escapeHtml(__('Telephone')) ?></label>
            <div class="control">
                <input type="tel" name="<?php echo $block->escapeHtml($methodCode) ?>[address_info][telephone]"
                       value="" title="<?php echo $block->escapeHtml(__('Telephone')) ?>"
                       class="input-text   required-entry" id="<?php
                        echo $block->escapeHtml($methodCode) ?>_telephone">
            </div>
        </div>                


    </fieldset>


    <fieldset class="fieldset">
        <h2 class="legend"><?php echo $block->escapeHtml(__('Card Information')) ?></h2>

        <div class="field cc_type required">
            <label for="<?php echo $block->escapeHtml($methodCode) ?>_cc_type" class="label">
<?php echo $block->escapeHtml(__('Credit Card Type')) ?></label>
            <div class="control">
                <select id="<?php echo $block->escapeHtml($methodCode) ?>_cc_type"
                        data-validate="{required:true, 'validate-cc-type-select':'#<?php
                        echo $block->escapeHtml($methodCode) ?>_cc_number'}"
                        name="<?php echo $block->escapeHtml($methodCode) ?>[payment_info][cc_type]"
                        class="required-entry validate-cc-type-select">
                    <option value=""><?php echo $block->escapeHtml(__('--Please Select--')) ?></option>
<?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName) : ?>
                        <option value="<?php echo $block->escapeHtml($_typeCode) ?>">
                        <?php echo $block->escapeHtml($_typeName) ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>

        <div class="field _cc_number required">
            <label for="<?php echo $block->escapeHtml($methodCode) ?>_cc_number" class="label">
<?php echo $block->escapeHtml(__('Credit Card Number')) ?></label>
            <div class="control">
                <input type="text" id="<?php echo $block->escapeHtml($methodCode) ?>_cc_number"
                       data-validate="{required:true, 'validate-number':true, 
                       'validate-cc-number':'#<?php echo $block->escapeHtml($methodCode) ?>_cc_type'}"
                       name="<?php echo $block->escapeHtml($methodCode) ?>[payment_info][cc_number]"
                       title="<?php echo $block->escapeHtml(__('Credit Card Number')) ?>"
                       class="input-text validate-cc-type" value="" autocomplete="off" />
            </div>
        </div>
        <div class="field expiration required">
            <label for="expiration" class="label"><?php echo $block->escapeHtml(__('Expiration Date')) ?></label>
            <div class="input-box">
                <div class="v-fix">
<?php $_ccExpMonth = '' ?>
                    <select id="<?php echo $block->escapeHtml($methodCode) ?>_expiration"
                            name="<?php echo $block->escapeHtml($methodCode) ?>[payment_info][cc_exp_month]"
                            data-validate="{'validate-cc-exp':'#<?php
                            echo $block->escapeHtml($methodCode) ?>_expiration_yr'}"
                            class="month validate-cc-exp required-entry"  style="width: 150px; margin-right: 10px;">
<?php foreach ($block->getCcMonths() as $k => $v) : ?>
                            <option value="<?php /* @noEscape */ echo $k ? $k : '' ?>"<?php if ($k
                            == $_ccExpMonth) : ?>
                                        selected="selected"<?php
endif
                                    ?>><?php /* @noEscape */ echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                                <?php $_ccExpYear = ''; ?>
                    <select id="<?php echo $block->escapeHtml($methodCode) ?>_expiration_yr"
                            name="<?php echo $block->escapeHtml($methodCode) ?>[payment_info][cc_exp_year]"
                            class="year required-entry " style="width: 150px;">
                    <?php foreach ($block->getCcYears() as $k => $v) : ?>
                            <option value="<?php
                            echo $block->escapeHtml($k) ? $block->escapeHtml($k) : ''
                    ?>"
                                    <?php if ($k
                                        == $_ccExpYear) :
                                        ?> selected="selected"
                                    <?php endif ?>>
                                    <?php echo $block->escapeHtml($v) ?></option>
                                <?php endforeach ?>
                    </select>
                </div>
            </div>
        </div>
<?php if ($block->hasVerification()) : ?>
            <div class="field cc_cid required">
                <label for="<?php echo $block->escapeHtml($methodCode) ?>_cc_cid" class="label">
            <?php echo $block->escapeHtml(__('Card Verification Number')) ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" title="<?php echo $block->escapeHtml(__('Card Verification Number')) ?>"
                               data-validate="{required:true, 'validate-cc-cvn':'#<?php
                                echo $block->escapeHtml($methodCode) ?>_cc_type'}"
                               class="input-text" id="<?php echo $block->escapeHtml($methodCode) ?>_cc_cid"
                               name="<?php echo $block->escapeHtml($methodCode) ?>[payment_info][cc_cid]"
                               value=""  autocomplete="off" />
                    </div>
                </div>
            </div>
<?php endif; ?>

        <div class="buttons-set">
            <input type="hidden" name="<?php echo $block->escapeHtml($methodCode) ?>[card_mode]" value="add" />
            <p class="back-link"><a href="<?php echo $block->escapeXssInUrl($block->getBackUrl()) ?>">
                    <small>&laquo; </small><?php echo $block->escapeHtml(__('Back')) ?></a></p>
            <button type="button"  onclick="saveCardForm()" 
                    title="<?php echo $block->escapeHtml(__('Save Card')) ?>"
                    class="button button action tocart primary"
                    id="monerisca_add_card_btn"><span>
                    <span><?php echo $block->escapeHtml(__('Save Card')) ?></span>
                </span>
            </button>
        </div>  
    </fieldset>
</form>

<script type="text/x-magento-init">
    {
    "#country": {
    "regionUpdater": {
    "optionalRegionAllowed": <?php
        /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all')
                ? 'true' : 'false');
?>,
    "regionListId": "#<?php /* @noEscape */ echo $methodCode ?>_region_id",
    "regionInputId": "#<?php /* @noEscape */ echo $methodCode ?>_state",
    "postcodeId": "#<?php /* @noEscape */ echo $methodCode ?>_zip",
    "form": "#monerisca_add_card",
    "regionJson": <?php /* @noEscape */
    echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson()
?>,
    "defaultRegion": "<?php /* @noEscape */ echo "0" ?>",
    "countriesWithOptionalZip": <?php
    /* @noEscape */
    echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true)
?>
    }
    }
    }
</script>