<?php die(); ?>
/app/code/Apptrian/ImageOptimizer/bin/win32/gifsicle.exe
/app/code/Apptrian/ImageOptimizer/bin/win32/optipng.exe
/app/code/Apptrian/ImageOptimizer/bin/win32/jpegoptim.exe
/app/code/Apptrian/ImageOptimizer/bin/win32/jpegtran.exe
/app/code/Apptrian/ImageOptimizer/bin/elf64/jpegoptim
/app/code/Apptrian/ImageOptimizer/bin/elf64/optipng
/app/code/Apptrian/ImageOptimizer/bin/elf64/jpegtran
/app/code/Apptrian/ImageOptimizer/bin/elf64/gifsicle
/app/code/Apptrian/ImageOptimizer/bin/win64/gifsicle.exe
/app/code/Apptrian/ImageOptimizer/bin/win64/optipng.exe
/app/code/Apptrian/ImageOptimizer/bin/win64/jpegoptim.exe
/app/code/Apptrian/ImageOptimizer/bin/win64/jpegtran.exe
/app/code/Apptrian/ImageOptimizer/bin/elf32/jpegoptim
/app/code/Apptrian/ImageOptimizer/bin/elf32/optipng
/app/code/Apptrian/ImageOptimizer/bin/elf32/jpegtran
/app/code/Apptrian/ImageOptimizer/bin/elf32/gifsicle
/vendor/magento/zendframework1/library/Zend/Service/WindowsAzure/CommandLine/Scaffolders/DefaultScaffolder/resources/PhpOnAzure.Web/resources/WebPICmdLine/WebpiCmdLine.exe
/vendor/symfony/console/Symfony/Component/Console/Resources/bin/hiddeninput.exe
